### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by slamdslam** [JuiMin/HALP#67]
Refer to notes for build:

https://docs.google.com/document/d/1HBv1MCxfPQZROFvANMPLLxZhLjra6MDwa0HySJ2sKO8/edit

**Comment by dlee20013** [comment]
PRIMARY-TWERK:

- [ ] In-board search for individual posts
- [ ] Dynamic search that pushes all subscriptions away 
- [ ] Set initial boards for the capstone but we can think about it afterwards

Secondary things:

- Suggested searches for recent searches 
- Multiple subscriptions on search page
- Search users
- Voice search meh
