### ISSUE TITLE
Posting

### ISSUE THREAD

**Issue by slamdslam** [JuiMin/HALP#68]
Refer to notes for build:

https://docs.google.com/document/d/1HBv1MCxfPQZROFvANMPLLxZhLjra6MDwa0HySJ2sKO8/edit

**Comment by dlee20013** [comment]
PRIMARY WORK:

- [ ] Keeping post tab as well as adding a post button for each board upon viewing 
- [ ] Image OR caption required
- [ ] Remove tags input 

Secondary work:

- Should picture be required?
- We can worry about tags later
